name: Automatic
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_first_job:
    name: AutoTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AutoTest
        run: |
         g++ -g AutomaticTest.cpp -o auto
         ./auto
         g++ -g AutomaticClangTidy.cpp -o auto
         ./auto
        
        
